language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - hhvm

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
